"""Gemini API client for multimodal structure analysis.

Sends a text prompt (and optionally a PNG image) to Google's Gemini API
and returns the raw text response.

Security: The API key is transmitted via the ``x-goog-api-key`` HTTP header
— never as a URL query parameter — so it does not appear in proxy logs,
server access logs, or OpenHEXA execution traces.
"""

import base64
import json

import requests

GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models"
DEFAULT_MODEL = "gemini-2.5-flash"


class GeminiClient:
    """Client for the Google Gemini generative-language API.

    The API key is stored as a private attribute and sent exclusively
    via the ``x-goog-api-key`` HTTP header (not as a URL parameter).

    Args:
        api_key: Google AI API key.
        model:   Gemini model identifier (default: ``gemini-2.5-flash``).
    """

    def __init__(self, api_key: str, model: str = DEFAULT_MODEL):
        """Initialise the client with credentials and model choice.

        Args:
            api_key: Google AI API key.
            model:   Gemini model identifier.
        """
        self._api_key = api_key
        self._model = model

    def generate(self, prompt: str, image_bytes: bytes | None = None) -> str:
        """Send a multimodal prompt to Gemini and return the text response.

        Args:
            prompt:      The text prompt to send.
            image_bytes: Optional PNG image bytes to include as inline data.

        Returns:
            The raw text generated by the model.

        Raises:
            requests.HTTPError: If the API returns a non-2xx status.
            RuntimeError:       If the response cannot be parsed.
        """
        url = f"{GEMINI_API_URL}/{self._model}:generateContent"

        parts: list[dict] = [{"text": prompt}]
        if image_bytes:
            parts.append(
                {
                    "inline_data": {
                        "mime_type": "image/png",
                        "data": base64.b64encode(image_bytes).decode("ascii"),
                    }
                }
            )

        request_body = {
            "contents": [{"parts": parts}],
            "generationConfig": {
                "temperature": 0.1,
                "maxOutputTokens": 65536,
            },
        }

        response = requests.post(
            url,
            headers={"x-goog-api-key": self._api_key},
            json=request_body,
            timeout=120,
        )
        response.raise_for_status()
        data = response.json()

        # Extract generated text.
        try:
            candidates = data["candidates"]
            generated_text = candidates[0]["content"]["parts"][0]["text"]
        except (KeyError, IndexError) as exc:
            raise RuntimeError(
                f"Could not parse Gemini response: {exc}\n"
                f"Response snippet: {json.dumps(data)[:500]}"
            ) from exc

        return generated_text

    def get_token_usage(self, response_data: dict) -> dict:
        """Extract token usage metadata from a raw Gemini response.

        Args:
            response_data: The full JSON response from the API.

        Returns:
            A dict with keys ``prompt_tokens``, ``response_tokens``,
            ``total_tokens`` (values may be ``None`` if not reported).
        """
        usage = response_data.get("usageMetadata", {})
        return {
            "prompt_tokens": usage.get("promptTokenCount"),
            "response_tokens": usage.get("candidatesTokenCount"),
            "total_tokens": usage.get("totalTokenCount"),
        }
