"""OpenHEXA Pipeline: Generate schema_validation.json from structure_proposal.json.

Reads a structure_proposal.json (produced by the AI structure analysis pipeline)
and an Excel template, then generates a schema_validation.json that the
validation pipeline can consume.

This pipeline is fully deterministic — it reshapes the AI-proposed structure
into the schema format, enriches it with example values and resolved data
validations from the actual Excel file.

This file is the thin orchestrator — all domain logic lives in:

- :mod:`text_helpers`        — canonical name generation and cell ref parsing
- :mod:`dv_resolver`         — data-validation extraction and resolution
- :mod:`section_processors`  — KeyValue / GroupedKeyValue / Records processors
- :mod:`schema_builder`      — schema assembly and deduplication
"""

from __future__ import annotations

import json
from pathlib import Path

import openpyxl
from openhexa.sdk import File, current_run, parameter, pipeline, workspace

from dv_resolver import DataValidationResolver
from schema_builder import SchemaBuilder

SCHEMA_OUTPUT_FILENAME = "schema_validation.json"


# ---------------------------------------------------------------------------
# Pipeline entry point
# ---------------------------------------------------------------------------


@pipeline("schema-validation", timeout=3600)
@parameter(
    "structure_proposal_file",
    name="Structure Proposal JSON",
    type=File,
    required=True,
    help="The structure_proposal.json file generated by the AI analysis pipeline.",
)
@parameter(
    "excel_file",
    name="Excel Template",
    type=File,
    required=True,
    help="The original Excel template (used for example values and validation resolution).",
)
@parameter(
    "sheet_name",
    name="Sheet Name",
    type=str,
    required=False,
    help="Sheet name to process. If empty, uses the sheet specified in the proposal.",
)
def schema_validation(
    structure_proposal_file: File,
    excel_file: File,
    sheet_name: str = None,
):
    """Generate schema_validation.json from a structure proposal and Excel template."""
    # -- Load proposal --
    current_run.log_info(f"Loading structure proposal: {structure_proposal_file}")
    with open(str(structure_proposal_file.path), encoding="utf-8") as proposal_file:
        proposal = json.load(proposal_file)

    current_run.log_info(
        f"Proposal loaded: {len(proposal.get('sections', []))} sections, "
        f"version {proposal.get('version', '?')}"
    )

    # -- Load workbooks --
    current_run.log_info(f"Loading Excel template: {excel_file}")
    excel_path = str(excel_file.path)
    workbook_values = openpyxl.load_workbook(excel_path, data_only=True)
    workbook_full = openpyxl.load_workbook(excel_path, data_only=False)

    # -- Select sheet --
    target_sheet = sheet_name or proposal.get("source_sheet")
    if target_sheet and target_sheet in workbook_values.sheetnames:
        worksheet_values = workbook_values[target_sheet]
        worksheet_full = workbook_full[target_sheet]
    else:
        worksheet_values = workbook_values[workbook_values.sheetnames[0]]
        worksheet_full = workbook_full[workbook_full.sheetnames[0]]
        current_run.log_info(
            f"Sheet '{target_sheet}' not found, using '{worksheet_values.title}'"
        )

    current_run.log_info(f"Processing sheet: '{worksheet_values.title}'")

    # -- Extract and resolve data validations --
    resolver = DataValidationResolver(worksheet_full, workbook_full)
    data_validation_map = resolver.extract()

    list_count = sum(
        1 for v in data_validation_map.values() if v.get("type") == "list"
    )
    indirect_count = sum(
        1 for v in data_validation_map.values() if v.get("type") == "indirect"
    )
    current_run.log_info(
        f"Data validations extracted: {list_count} list dropdowns, "
        f"{indirect_count} INDIRECT (conditional) dropdowns"
    )

    conditional_map = resolver.resolve_indirect_dependencies()
    if conditional_map:
        summaries = [
            f"{col} depends on {info['depends_on_column']}"
            for col, info in conditional_map.items()
        ]
        current_run.log_info(
            f"Conditional dropdowns resolved: {', '.join(summaries)}"
        )

    workbook_full.close()

    # -- Enrich with pre-resolved values from the proposal (fallback) --
    resolver.merge_proposal_validations(proposal)

    # -- Build schema --
    current_run.log_info("Generating schema from structure proposal...")
    builder = SchemaBuilder(
        proposal,
        worksheet_values,
        resolver.data_validation_map,
        conditional_map,
    )
    schema = builder.build()

    # Emit deferred log messages from the builder
    for message in builder.log_messages:
        current_run.log_info(message)

    # -- Write output --
    output_path = Path(workspace.files_path) / SCHEMA_OUTPUT_FILENAME
    with output_path.open("w", encoding="utf-8") as output_file:
        json.dump(schema, output_file, indent=2, ensure_ascii=False)

    current_run.log_info(f"Schema written to: {output_path}")

    # -- Summary --
    label_count = sum(
        len([k for k in v if not k.startswith("_")])
        for k, v in schema.get("label_fields", {}).items()
        if isinstance(v, dict) and not k.endswith("_columns")
    )
    header_column_count = sum(
        len(schema["header_modules"][k].get("columns", []))
        for k in schema.get("header_modules", {})
        if not k.startswith("_") and k != "mismatch_message_template"
    )
    current_run.log_info(
        f"Schema summary: {label_count} label fields, "
        f"{header_column_count} header columns"
    )

    workbook_values.close()


if __name__ == "__main__":
    schema_validation()
